# ===================================
#  Extended Profile Field Definitions
# ===================================

phone:
    label: Phone
    tab: Profile
    span: left

company:
    label: Company
    tab: Profile
    span: left

city:
    label: City
    tab: Profile
    span: left

zip:
    label: Zip
    tab: Profile
    span: right

country:
    label: Country
    placeholder: -- select country --
    type: dropdown
    tab: Profile
    span: left

state:
    label: State
    placeholder: -- select state --
    type: dropdown
    tab: Profile
    span: right
    dependsOn: country
